"""
初始数据 - 模拟用户和项目
"""

from datetime import datetime, timedelta
from sqlalchemy import select
from app.models.models import (
    User, Project, GovProject, UserRole, ProjectStatus, GovProjectStatus
)
from app.core.database import async_session


async def seed_database(session):
    """填充初始数据"""
    # 检查是否已有数据
    result = await session.execute(select(User).limit(1))
    if result.scalar_one_or_none():
        return  # 已有数据，跳过

    # ==================== 创建模拟用户 ====================
    users_data = [
        {
            "username": "tech_alice",
            "email": "alice@techstar.com",
            "password_hash": "hashed_password_1",
            "role": UserRole.SUPPLIER,
            "display_name": "张晓明",
            "company": "星辰科技有限公司",
            "bio": "专注AI算法开发10年，团队20人，擅长计算机视觉和NLP",
            "skills": ["计算机视觉", "NLP", "深度学习", "PyTorch", "TensorFlow"],
            "industries": ["人工智能", "医疗健康", "智能制造"],
            "location": "北京",
            "phone": "13800138001",
            "rating": 4.8,
            "rating_count": 23,
            "is_verified": True,
        },
        {
            "username": "dev_bob",
            "email": "bob@innovate.com",
            "password_hash": "hashed_password_2",
            "role": UserRole.SUPPLIER,
            "display_name": "李伟",
            "company": "创新工场技术团队",
            "bio": "全栈开发团队，擅长Web/移动端开发，交付过50+项目",
            "skills": ["React", "Node.js", "Python", "Flutter", "AWS"],
            "industries": ["互联网", "金融科技", "电商"],
            "location": "上海",
            "phone": "13800138002",
            "rating": 4.6,
            "rating_count": 18,
            "is_verified": True,
        },
        {
            "username": "data_carol",
            "email": "carol@datawise.com",
            "password_hash": "hashed_password_3",
            "role": UserRole.SUPPLIER,
            "display_name": "王芳",
            "company": "数据智慧咨询",
            "bio": "大数据分析专家，为50+企业提供数据解决方案",
            "skills": ["数据分析", "Spark", "Hadoop", "BI", "Python"],
            "industries": ["金融", "零售", "制造"],
            "location": "深圳",
            "phone": "13800138003",
            "rating": 4.9,
            "rating_count": 31,
            "is_verified": True,
        },
        {
            "username": "gov_david",
            "email": "david@jiangsu-gov.com",
            "password_hash": "hashed_password_4",
            "role": UserRole.DEMANDER,
            "display_name": "陈建国",
            "company": "江苏省国信集团",
            "bio": "负责集团AI技术引进和数字化转型项目",
            "skills": ["项目管理", "技术评估"],
            "industries": ["能源", "金融"],
            "location": "南京",
            "phone": "13800138004",
            "rating": 4.7,
            "rating_count": 12,
            "is_verified": True,
        },
        {
            "username": "startup_eve",
            "email": "eve@quantum-leap.com",
            "password_hash": "hashed_password_5",
            "role": UserRole.BOTH,
            "display_name": "刘思远",
            "company": "量子飞跃科技",
            "bio": "90后创业者，专注AI+物联网解决方案，已获A轮融资",
            "skills": ["IoT", "嵌入式", "AIoT", "边缘计算", "5G"],
            "industries": ["物联网", "智慧城市", "工业互联网"],
            "location": "杭州",
            "phone": "13800138005",
            "rating": 4.5,
            "rating_count": 8,
            "is_verified": True,
        },
    ]

    users = []
    for ud in users_data:
        user = User(**ud)
        session.add(user)
        users.append(user)

    await session.flush()

    # ==================== 创建需求项目 ====================
    projects_data = [
        {
            "title": "智能客服系统开发",
            "description": "需要开发一套基于大语言模型的智能客服系统，支持多轮对话、意图识别、情感分析，集成到现有CRM系统中。要求支持日均10万+会话量。",
            "category": "AI应用",
            "industry": "金融科技",
            "demander_id": users[3].id,
            "budget_min": 50,
            "budget_max": 100,
            "deadline": datetime.utcnow() + timedelta(days=30),
            "required_skills": ["NLP", "大语言模型", "Python", "FastAPI"],
            "status": ProjectStatus.OPEN,
            "is_featured": True,
        },
        {
            "title": "工业视觉质检系统",
            "description": "为生产线开发基于计算机视觉的产品缺陷检测系统，需要实时检测、高精度识别各类缺陷，集成到MES系统。",
            "category": "AI应用",
            "industry": "智能制造",
            "demander_id": users[3].id,
            "budget_min": 80,
            "budget_max": 150,
            "deadline": datetime.utcnow() + timedelta(days=45),
            "required_skills": ["计算机视觉", "OpenCV", "深度学习", "边缘部署"],
            "status": ProjectStatus.OPEN,
            "is_featured": True,
        },
        {
            "title": "企业数据中台建设",
            "description": "建设统一的数据中台，整合各业务系统数据，实现数据标准化、数据治理、数据服务化。",
            "category": "数据工程",
            "industry": "集团企业",
            "demander_id": users[3].id,
            "budget_min": 200,
            "budget_max": 500,
            "deadline": datetime.utcnow() + timedelta(days=60),
            "required_skills": ["数据架构", "Spark", "Hadoop", "数据治理"],
            "status": ProjectStatus.OPEN,
        },
        {
            "title": "小程序商城开发",
            "description": "开发微信小程序商城，包含商品管理、购物车、订单系统、支付对接、营销活动模块。",
            "category": "应用开发",
            "industry": "电商零售",
            "demander_id": users[3].id,
            "budget_min": 30,
            "budget_max": 60,
            "deadline": datetime.utcnow() + timedelta(days=20),
            "required_skills": ["微信小程序", "Node.js", "MySQL", "Redis"],
            "status": ProjectStatus.OPEN,
            "is_urgent": True,
        },
        {
            "title": "智慧园区IoT平台",
            "description": "开发智慧园区物联网管理平台，包含设备接入、数据采集、规则引擎、可视化大屏等模块。",
            "category": "物联网",
            "industry": "智慧城市",
            "demander_id": users[4].id,
            "budget_min": 100,
            "budget_max": 200,
            "deadline": datetime.utcnow() + timedelta(days=40),
            "required_skills": ["IoT", "MQTT", "时序数据库", "Vue.js"],
            "status": ProjectStatus.OPEN,
        },
    ]

    for pd in projects_data:
        project = Project(**pd)
        session.add(project)

    # ==================== 创建揭榜挂帅政府项目 ====================
    gov_projects_data = [
        {
            "title": "海上风电场智能运维系统",
            "description": "融合人工智能技术，在海上风电项目中搭建智能运维系统，实现风机状态实时评估、远程运维、无人巡检、故障预测维护。系统需要支持50+台风机的实时监控，故障预警准确率达到95%以上。",
            "publisher": "江苏省国信集团有限公司",
            "publisher_contact": "叶兴沛 18251862103",
            "industry": "新能源",
            "tags": ["海上风电", "智能运维", "无人巡检", "预测性维护"],
            "budget_min": 200,
            "budget_max": 300,
            "deadline": datetime(2026, 3, 28),
            "tech_requirements": "需要具备海上风电运维经验，熟悉风机结构和运行原理，掌握计算机视觉和时序数据分析技术。",
            "required_skills": ["计算机视觉", "时序分析", "IoT", "边缘计算"],
            "status": GovProjectStatus.APPLYING,
            "is_featured": True,
        },
        {
            "title": "高速公路智慧化综合管理平台",
            "description": "高速公路全路段智慧化改造，包括智慧收费（ETC+无感支付）、智慧监控（AI视频分析）、智慧服务区、车路协同（V2X）、应急指挥调度。覆盖500+公里高速路段。",
            "publisher": "江苏交通控股有限公司",
            "publisher_contact": "赵明 13951001234",
            "industry": "交通",
            "tags": ["智慧高速", "车路协同", "智能监控", "V2X"],
            "budget_min": 500,
            "budget_max": 1000,
            "deadline": datetime(2026, 5, 15),
            "tech_requirements": "需要具备智慧交通项目经验，熟悉高速公路业务流程，掌握视频AI分析和车路协同技术。",
            "required_skills": ["视频AI", "V2X", "大数据", "GIS"],
            "status": GovProjectStatus.APPLYING,
            "is_featured": True,
        },
        {
            "title": "媒体产业全链路智能协同平台",
            "description": "媒体内容生产全流程智能化平台，包括智能选题（热点发现）、内容生成（AIGC）、智能审核（合规+质量）、智能分发（多渠道）、效果分析（数据驱动）。",
            "publisher": "江苏省广播电视集团有限公司",
            "publisher_contact": "周华 13812345678",
            "industry": "文化传媒",
            "tags": ["媒体智能化", "内容生产", "AIGC", "智能审核"],
            "budget_min": 100,
            "budget_max": 200,
            "deadline": datetime(2026, 4, 25),
            "tech_requirements": "需要具备媒体行业经验，熟悉内容审核规范，掌握NLP和AIGC技术。",
            "required_skills": ["NLP", "AIGC", "内容审核", "推荐算法"],
            "status": GovProjectStatus.APPLYING,
            "is_featured": True,
        },
        {
            "title": "AI驱动的纺织设计系统",
            "description": "利用AI技术辅助纺织品设计，包括图案智能生成（GAN/Diffusion）、色彩搭配推荐、款式设计辅助、面料仿真预览。需要支持10万+图案库的检索和生成。",
            "publisher": "江苏省苏豪控股集团有限公司",
            "publisher_contact": "孙丽 15951009876",
            "industry": "纺织服装",
            "tags": ["纺织设计", "AI生成", "GAN", "创意设计"],
            "budget_min": 80,
            "budget_max": 150,
            "deadline": datetime(2026, 5, 30),
            "tech_requirements": "需要具备图像生成经验，熟悉GAN/Diffusion模型，了解纺织行业设计流程。",
            "required_skills": ["GAN", "Diffusion", "图像生成", "推荐系统"],
            "status": GovProjectStatus.APPLYING,
        },
        {
            "title": "智能验布与面料缺陷检测系统",
            "description": "基于计算机视觉的智能验布系统，自动检测面料缺陷（断经、断纬、油污、色差等），检测速度≥30m/min，准确率≥98%。",
            "publisher": "江苏省苏豪控股集团有限公司",
            "publisher_contact": "孙丽 15951009876",
            "industry": "纺织服装",
            "tags": ["面料检测", "缺陷识别", "智能质检", "计算机视觉"],
            "budget_min": 50,
            "budget_max": 100,
            "deadline": datetime(2026, 4, 20),
            "tech_requirements": "需要具备工业视觉检测经验，熟悉面料缺陷类型，掌握实时检测算法。",
            "required_skills": ["计算机视觉", "实时检测", "深度学习", "边缘部署"],
            "status": GovProjectStatus.APPLYING,
        },
        {
            "title": "智慧农业无人机巡检平台",
            "description": "农业无人机巡检及数据分析平台，包括作物监测（多光谱）、病虫害识别、产量预测、农事决策。支持10万亩+农田管理。",
            "publisher": "江苏省农垦集团有限公司",
            "publisher_contact": "钱明 13776543210",
            "industry": "农业",
            "tags": ["智慧农业", "无人机", "精准农业", "遥感"],
            "budget_min": 100,
            "budget_max": 200,
            "deadline": datetime(2026, 6, 10),
            "tech_requirements": "需要具备无人机应用经验，熟悉多光谱遥感，掌握农业AI模型。",
            "required_skills": ["无人机", "遥感", "GIS", "深度学习"],
            "status": GovProjectStatus.APPLYING,
            "is_featured": True,
        },
        {
            "title": "煤矿智能洗选质量控制系统",
            "description": "煤炭洗选工艺智能化控制系统，实现原煤检测（灰分、硫分在线分析）、工艺参数优化、产品质量监控、能耗管理。处理能力500万吨/年。",
            "publisher": "徐州矿务集团有限公司",
            "publisher_contact": "吴强 15876543210",
            "industry": "煤炭",
            "tags": ["煤炭洗选", "智能优化", "质量提升", "在线检测"],
            "budget_min": 200,
            "budget_max": 400,
            "deadline": datetime(2026, 6, 25),
            "tech_requirements": "需要具备煤炭行业经验，熟悉洗选工艺，掌握在线检测和优化控制技术。",
            "required_skills": ["过程控制", "在线检测", "优化算法", "DCS"],
            "status": GovProjectStatus.APPLYING,
        },
        {
            "title": "旧房改造AI协同设计平台",
            "description": "旧房改造AI协同设计平台，包括结构评估（3D扫描+BIM）、方案生成（AI辅助设计）、BIM建模、施工管理、成本估算。支持1000+户型模板。",
            "publisher": "中国江苏国际经济技术合作集团有限公司",
            "publisher_contact": "郑华 13654321098",
            "industry": "建筑工程",
            "tags": ["旧房改造", "智能建筑", "BIM", "城市更新"],
            "budget_min": 100,
            "budget_max": 200,
            "deadline": datetime(2026, 7, 8),
            "tech_requirements": "需要具备建筑设计经验，熟悉BIM技术，掌握3D扫描和AI设计工具。",
            "required_skills": ["BIM", "3D建模", "AI设计", "Revit"],
            "status": GovProjectStatus.APPLYING,
        },
        {
            "title": "燃气轮机智能运维系统",
            "description": "300MW级燃气轮机发电机组智能运维系统，实现设备状态监测（振动、温度、压力）、故障预警、预测性维护、运行优化。",
            "publisher": "江苏省国信集团有限公司",
            "publisher_contact": "叶兴沛 18251862103",
            "industry": "能源",
            "tags": ["燃气轮机", "智能运维", "故障预警", "PHM"],
            "budget_min": 300,
            "budget_max": 500,
            "deadline": datetime(2026, 4, 30),
            "tech_requirements": "需要具备旋转机械运维经验，熟悉燃气轮机结构，掌握振动分析和PHM技术。",
            "required_skills": ["PHM", "振动分析", "时序预测", "IoT"],
            "status": GovProjectStatus.APPLYING,
        },
        {
            "title": "智慧高速出行服务APP",
            "description": "基于AI的个性化出行服务系统，包括智能路线规划、路况预测（准确率>90%）、服务区推荐、无感支付、紧急救援呼叫。",
            "publisher": "江苏交通控股有限公司",
            "publisher_contact": "赵明 13951001234",
            "industry": "交通",
            "tags": ["出行服务", "个性化推荐", "智慧高速", "导航"],
            "budget_min": 200,
            "budget_max": 400,
            "deadline": datetime(2026, 7, 20),
            "tech_requirements": "需要具备出行类APP开发经验，熟悉导航算法，掌握路况预测技术。",
            "required_skills": ["移动开发", "推荐算法", "GIS", "机器学习"],
            "status": GovProjectStatus.APPLYING,
        },
        {
            "title": "安全生产智能管控平台",
            "description": "企业安全生产智能管控平台，包括视频AI监测（人员行为识别）、隐患排查（自动派单）、风险预警（多源数据融合）、应急指挥（数字孪生）。",
            "publisher": "江苏省苏豪控股集团有限公司",
            "publisher_contact": "孙丽 15951009876",
            "industry": "安全生产",
            "tags": ["安全生产", "风险管控", "视频AI", "数字孪生"],
            "budget_min": 150,
            "budget_max": 250,
            "deadline": datetime(2026, 5, 18),
            "tech_requirements": "需要具备安全生产领域经验，熟悉视频分析，掌握数字孪生技术。",
            "required_skills": ["视频AI", "数字孪生", "知识图谱", "预警系统"],
            "status": GovProjectStatus.APPLYING,
        },
        {
            "title": "煤矿大数据智能决策系统",
            "description": "煤矿大数据智能决策支持系统，包括生产调度优化、安全评估（风险画像）、设备管理（全生命周期）、成本分析（精细化核算）。",
            "publisher": "徐州矿务集团有限公司",
            "publisher_contact": "吴强 15876543210",
            "industry": "煤炭",
            "tags": ["煤矿大数据", "智能决策", "安全生产", "数字矿山"],
            "budget_min": 150,
            "budget_max": 300,
            "deadline": datetime(2026, 8, 1),
            "tech_requirements": "需要具备煤矿行业经验，熟悉矿山生产流程，掌握大数据分析技术。",
            "required_skills": ["大数据", "数据挖掘", "优化算法", "可视化"],
            "status": GovProjectStatus.APPLYING,
        },
    ]

    for gpd in gov_projects_data:
        gp = GovProject(**gpd)
        session.add(gp)

    await session.commit()
    print("✅ 初始数据填充完成：5个用户 + 5个项目 + 12个政府项目")
